const AppointmentErrorCodes = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  RELATED_ENTITY_NOT_FOUND: 'APPOINTMENT_RELATED_ENTITY_NOT_FOUND',
  SCHEDULE_CONFLICT: 'APPOINTMENT_SCHEDULE_CONFLICT',
  INVALID_STATUS_TRANSITION: 'APPOINTMENT_INVALID_STATUS_TRANSITION',
  PAST_DATE: 'APPOINTMENT_PAST_DATE',
});

module.exports = {
  AppointmentErrorCodes,
};
